name: Setup
description: Set up Node.js, cache and install dependencies
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '18.12.1'
runs:
  using: composite
  steps:
    # Requires git checkout with fetch depth 0
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Cypress executable cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/Cypress
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-

    - name: Install dependencies
      shell: bash
      run: pnpm --no-progress --non-interactive i
      env:
        HUSKY_SKIP_INSTALL: 'true'
