name: Stream Components - Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
#        with:
#          json-opts: '{"dry-run": true}'
